---
# TEST PIPELINE - Deploys HTTP server instead of CronJob
# Use this to verify secrets are properly injected
# To use: rename this to .drone.yml (backup the original first)

kind: pipeline
type: kubernetes
name: github-metrics-test
platform:
  arch: arm64

trigger:
  branch:
  - main

steps:
  - name: publish
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: docs/github-metrics
      dockerfile: github-metrics/Dockerfile.test  # Use test Dockerfile
      tags:
      - test-${DRONE_COMMIT_SHA:0:7}
      - test-latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
      - push

  - name: deploy-staging
    image: public.ecr.aws/kanopy/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.25.0
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: github-metrics-test
      values: >
        arch=arm64,
        image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/github-metrics,
        image.tag=test-${DRONE_COMMIT_SHA:0:7},
        secretsRef=github-metrics-secrets,
        configRef=github-metrics-config
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      event:
      - push

