---
kind: pipeline
type: kubernetes
name: test

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: test
    image: node:20-alpine
    commands:
      - cd github-metrics
      - npm ci
      - node --version
      - npm --version
      - echo "Validating package.json and dependencies..."

---
depends_on: ['test']
kind: pipeline
type: kubernetes
name: production-build

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  # Builds and publishes Docker image for production
  - name: publish-production
    image: plugins/kaniko-ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: docs/github-metrics
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      context: github-metrics
      dockerfile: github-metrics/Dockerfile

---
depends_on: ['production-build']
kind: pipeline
type: kubernetes
name: production-deploy

trigger:
  branch:
    - main
  event:
    - push
    - tag

steps:
  # Deploys cronjob to production using Helm
  - name: deploy-production
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/cronjob
      chart_version: 1.21.2
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: github-metrics
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/github-metrics
      values_files: ['github-metrics/cronjobs.yml']
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token